### ISSUE TITLE
How to install this app on windows 10? 

### ISSUE THREAD

**Issue by Droyk** [Microsoft/Windows-appsample-rssreader#2]
Hey as the title says how to install this app on windows 10? 
I have windows 10 Pro Version 1607 (OS Build 14393.51)
Is there is anyway to install this through Windows store?

if there isn't then why you didn't published this good UI app on store?
if there is then why I can't find it?

**Comment by KarlErickson** [comment]
Hi Droyk - thanks for the comment! We haven't published this app to the store, but it is something we are currently investigating. So, currently the only way to install is through VS or side-loading.

**Comment by VitouSrun** [comment]
When I try to install it through side-loading it seem cannot connect to the Internet because all feeds are down. If there are something wrong with my PC how can I fix it? thanks

**Comment by KarlErickson** [comment]
Hi VitouSrun - I'm not sure what's going on here, but I can suggest some things to try. Does it only occur when you side-load, or does it also happen when you run it from VS with the debugger attached? This error state occurs when your network connection is down, but if you can access other network resources (for example, through your browser), then you should check the project's Package.appxmanifest file. In the manifest designer, make sure that the Internet (Client) capability is selected in the Capabilities list. (This should be selected already, but maybe you have accidentally unselected it somehow.) Other than that, I'm not sure what to suggest. I hope this helps!

**Comment by VitouSrun** [comment]
Thanks for reply me! I checked the project's Package.appxmanifest file already and the Internet (Client) capability is selected. And one more thing when I try to do the same thing with my friend's PC it's work correctly. That's why I think does it need more component or framework to install on my PC?

**Comment by KarlErickson** [comment]
It should not need any additional component or framework. You could try creating a simplified repro, like a new project with just a WebView control pointing to some web site. If you can't get any networking code to work correctly, but the network works fine otherwise, then you might try reinstalling the SDK.

**Comment by VitouSrun** [comment]
Sorry I'm not sure whether which SDK I might try reinstalling. And now I created new project like you said and try installing window 10 SDK but it still not work.

**Comment by KarlErickson** [comment]
You can find downloads for the latest SDK and tools at https://developer.microsoft.com/en-us/windows/downloads. Make sure your copy of Windows and all these tools are up to date.
If that doesn't fix the problem, then you could try uninstalling and then reinstalling the tools and SDK. If necessary, you can use a tool like https://github.com/Microsoft/VisualStudioUninstaller to do a clean uninstall before you reinstall. That's not guaranteed to clean up everything, though, so if that doesn't work, you can always try wiping your PC and reinstalling Windows and everything else. I'm not sure what else to suggest, but you might also ask on a forum like the ones at https://developer.microsoft.com/en-us/windows/support or at http://stackoverflow.com. Good luck!

**Comment by VitouSrun** [comment]
Yes I will try. Thanks you very much for you help!
