### ISSUE TITLE
Always open the rss article in web browser and not in webview

### ISSUE THREAD

**Issue by jmdkent** [Microsoft/Windows-appsample-rssreader#4]
Hi!!
Your code is awesome, but I can't figure it out why always when I click an article on the app, it opens it on first on the default browser and then in the app on the webview part.
is there a reason this is happening, what I'm looking for is to open it only on the webview part on the app, not in the default browser, could you point me in the right direction.
thanks

**Comment by KarlErickson** [comment]
Hi jmdkent - I'm working on a fix for this and a few other things. I should have an update ready this week. Thanks for the feedback!

**Comment by KarlErickson** [comment]
Fixed.
