### ISSUE TITLE
Sample builds OK but won't run

### ISSUE THREAD

**Issue by yannduran** [microsoft/Windows-appsample-rssreader#8]
App freshly cloned
Windows SDK 1809 installed

![image](https://user-images.githubusercontent.com/2031126/57432536-7f11e800-7279-11e9-8eb0-d7f679c0319a.png)

**F5/Ctrl-F5:**

Build has been canceled.DEP6957: 
- Failed to connect to device '127.0.0.1' using Universal Authentication. 
- Please verify the correct remote authentication mode is specified in the project debug settings. 
- COMException - No connection could be made because the target machine actively refused it.
- (Exception from HRESULT: 0x8007274D) [0x8007274D]

**Comment by Karl-Bridge-Microsoft** [comment]
Closing issue due to age. Please open a new issue if required.
